# Meta data
name:         Eshen Salvatore Saund
authors:      Eshen Saund
description:  A blog I do about my amazing ICT lessons 

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://goratchet.com
